# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.25"

    # Test the main module
    - name: Test main module
      run: go test -v ./...

    # Test each submodule under store/*
    - name: Test submodules
      run: |
        for dir in ./*store; do
          if [ -f "$dir/go.mod" ]; then
            echo "===> Testing $dir"
            cd "$dir"
            go test -v ./...
            cd - >/dev/null
          fi
        done




